### ISSUE TITLE
Ability to copy including link

### ISSUE THREAD

**Issue by milansvehla** [daemonLibra/JiraIssueCopyData#1]
Hi,
Thanks for the great extension. Would you be open to adding a link wrapping the issue number? It could be as simple as replacing 
```navigator.clipboard.writeText(`[${data['key']}] ${data['fields']['summary']}`)```
with 
```navigator.clipboard.writeText(`[<a href="https://${GetSubDomain()}.atlassian.net/browse/${data['key']}">${data['key']}</a>] ${data['fields']['summary']}`)``` (untested)
and then probably some flag which would turn this on/off in extension settings to preserve current non-link functionality.
It would make the extension even more usefull.
Thanks for considering.

**Comment by daemonLibra** [comment]
Hi, i was looking in Jira and they already have a "button" where u can easily copy the issue link. It should be in the top right corner if you hover over the issue id. 
![grafik](https://user-images.githubusercontent.com/40869874/204378002-71ee50ef-f2f6-4ef8-a9df-804dea20d19b.png)

There will be soonish an update where i ll add customisation to the add-on so that you could change the button functionality how ever u want. 
Cheers

**Comment by james-hu** [comment]
@daemonLibra Hi, The problem with existing "Copy link to issue" feature provided by Atlassin is that it does not include the title of the ticket. That leaves us with this options:

- Only the link -> Use "Copy link to issue"
- Ticket number/ID with the link -> Select "AC-4931" in the example above and copy it
- Pure text ticket number/ID and the title -> Use your Chrome extension

However, what if I want something like this: [AC-4931](https://example.com) Add a new page to place the order
Or this: [AC-4931 Add a new page to place the order](https://example.com)
?
